apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: be-law-ai-app           #child app name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Kunalm-1810/k8s-arcgocd-config-repo.git'         # Repo containing child apps
    targetRevision: main
    path:/ansible-helm/Infra/k8s/backend                                 # path of  app manifests in the repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  